name: Scrap avec Playwright

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer Playwright
        run: |
          pip install playwright
          playwright install chromium

      - name: Exécuter le scraper
        run: python scraper.py

      - name: Commit et push JSON
        run: |
          git config user.name "Kevin Bot"
          git config user.email "kevin@example.com"
          git add urgences.json
          git commit -m "update json" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
